query getProducts($first: Int = 4) {
  products(first: $first) {
    nodes {
      handle
      title
      featuredImage {
        id
        url
      }
      variants(first: 1) {
        nodes {
          price {
            amount
            currencyCode
          }
        }
      }
    }
  }
}
